### ISSUE TITLE
please provide me access to download dataset from google drive

### ISSUE THREAD

**Issue by shreyaulligeri** [darshandagly/Fake-Review-Detection#1]
please give me access to download data set

**Comment by vamsiINFJ** [comment]
Yes bro, I too need it. Please

**Comment by vishak007** [comment]
please grant me the permission to access

**Comment by darshandagly** [comment]
https://drive.google.com/drive/folders/1Te4MigL6K8AyOyQDNu3ADupXur1Y_EWA?usp=sharing

I'll update the link in the readme to the correct one.
