### ISSUE TITLE
Please provide me access to download dataset from google drive

### ISSUE THREAD

**Issue by huyennt62** [darshandagly/Fake-Review-Detection#2]
Please provide me access to download dataset from google drive. Thank you!

**Comment by darshandagly** [comment]
https://drive.google.com/drive/folders/1Te4MigL6K8AyOyQDNu3ADupXur1Y_EWA?usp=sharing

**Comment by huyennt62** [comment]
Dear Darshan Dagly,
The folder you sent me is empty. Could you please check it again for me?
Thank you.

Vào Th 7, 13 thg 11, 2021 vào lúc 10:46 Darshan Dagly <
***@***.***> đã viết:
